# https://github.com/deadc0de6/dotdrop/wiki/installation
#
# git su
# pip3 install --user -r dotdrop/requirements.txt
# ./dotdrop/bootstrap.sh
# ./dotdrop.sh install --cfg=/mnt/Users/matt.dentremont/Dotfiles/config-windows.yaml
#
variables:
  beyond_compare_path: C:\\Program Files\\Beyond Compare 4\\BComp.exe

config:
  backup: true
  banner: true
  create: true
  dotpath: /mnt/c/Users/matt.dentremont/Dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  workdir: /mnt/c/Users/matt.dentremont/.config/dotdrop

dotfiles:
  bcomp:
    dst: /mnt/c/Users/matt.dentremont/bin/bcomp
    src: platform-specific-bin/bcomp-windows
  bin:
    dst: /mnt/c/Users/matt.dentremont/bin
    src: bin
    cmpignore:
      - "bcomp*"
    upignore:
      - "bcomp*"
  gitconfig:
    dst: /mnt/c/Users/matt.dentremont/.gitconfig
    src: gitconfig
  gitignore_global:
    dst: /mnt/c/Users/matt.dentremont/.gitignore_global
    src: gitignore_global
  ssh:
    dst: /mnt/c/Users/matt.dentremont/.ssh
    src: ssh
  vim:
    dst: /mnt/c/Users/matt.dentremont/.vim
    instignore:
      - "backup"
      - "bundle"
      - "colors"
    cmpignore:
      - "backup"
      - "bundle"
      - "colors"
    upignore:
      - "backup"
      - "bundle"
      - "colors"
  vimrc:
    dst: /mnt/c/Users/matt.dentremont/.vimrc
    src: vimrc
  nvim:
    dst: /mnt/c/Users/matt.dentremont/AppData/Local/nvim/init.vim
    src: config/nvim/init.vim
  nvim-autoload:
    dst: /mnt/c/Users/matt.dentremont/AppData/Local/nvim/autoload/plug.vim
    src: vim/autoload/plug.vim

profiles:
  TG-1433:
    dotfiles:
    - ALL
