config:
  backup: true
  banner: true
  create: true
  dotpath: ~/Dotfiles
  keepdot: false
  link_dotfile_default: link
  link_on_import: link
dotfiles:
  bcomp:
    dst: ~/bin/bcomp
    src: platform-specific-bin/bcomp-linux
  bin:
    dst: ~/bin/
    src: bin
    link: link_children
    cmpignore:
    - bcomp*
    upignore:
    - bcomp*
  checkoutmanager.cfg:
    dst: ~/.checkoutmanager.cfg
    src: checkoutmanager.cfg
  com.googlecode.iterm2.plist:
    dst: ~/.com.googlecode.iterm2.plist
    src: com.googlecode.iterm2.plist
  fish:
    dst: ~/.config/fish
    src: fish
  gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  gitignore_global:
    dst: ~/.gitignore_global
    src: gitignore_global
  karabiner.json:
    src: config/karabiner/karabiner.json
    dst: ~/.config/karabiner/karabiner.json
    chmod: '600'
  oh-my-zsh:
    src: oh-my-zsh
    dst: ~/.oh-my-zsh
  ssh:
    dst: ~/.ssh
    src: ssh
  thefuck:
    dst: ~/.config/thefuck
    src: config/thefuck
  tmux:
    dst: ~/.tmux
    src: tmux
  tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  zgenomrc:
    dst: ~/.zgenomrc
    src: zgenomrc
  zsh.d:
    dst: ~/.zsh.d
    src: zsh.d
  zshenv:
    dst: ~/.zshenv
    src: zshenv
  zshrc:
    dst: ~/.zshrc
    src: zshrc
  nvim:
    dst: ~/.config/nvim
    src: config/nvim
  wezterm:
    dst: ~/.config/wezterm
    src: config/wezterm
profiles:
  Matts-MBP:
    dotfiles:
    - ALL
  spin:
    dotfiles:
    - ALL
