# https://github.com/deadc0de6/dotdrop/wiki/installation
#
# git su
# pip3 install --user -r dotdrop/requirements.txt
# ./dotdrop/bootstrap.sh
# ./dotdrop.sh install --cfg=~/Dotfiles/config-linux.yaml
#
config:
  backup: true
  banner: true
  create: true
  dotpath: ~/Dotfiles
  keepdot: false
  link_dotfile_default: link
  link_on_import: link

dotfiles:
  bcomp:
    dst: ~/bin/bcomp
    src: platform-specific-bin/bcomp-linux
  bin:
    dst: ~/bin/
    src: bin
    link: link_children
    cmpignore:
      - 'bcomp*'
    upignore:
      - 'bcomp*'
  checkoutmanager.cfg:
    dst: ~/.checkoutmanager.cfg
    src: checkoutmanager.cfg
  com.googlecode.iterm2.plist:
    dst: ~/.com.googlecode.iterm2.plist
    src: com.googlecode.iterm2.plist
  fish:
    dst: ~/.config/fish
    src: fish
  gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  gitignore_global:
    dst: ~/.gitignore_global
    src: gitignore_global
  oh-my-zsh:
    src: oh-my-zsh
    dst: ~/.oh-my-zsh
  ssh:
    dst: ~/.ssh
    src: ssh
  thefuck:
    dst: ~/.config/thefuck
    src: config/thefuck
  tmux:
    dst: ~/.tmux
    src: tmux
  tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  vim:
    dst: ~/.vim
    src: vim
    link: link_children
    cmpignore:
      - 'backup'
      - 'bundle'
      - 'colors'
      - 'doc'
    upignore:
      - 'backup'
      - 'bundle'
      - 'colors'
      - 'doc'
    instignore:
      - 'backup'
      - 'bundle'
      - 'colors'
      - 'doc'
  vimrc:
    dst: ~/.vimrc
    src: vimrc
  zgenomrc:
    dst: ~/.zgenomrc
    src: zgenomrc
  zsh.d:
    dst: ~/.zsh.d
    src: zsh.d
  zshenv:
    dst: ~/.zshenv
    src: zshenv
  zshrc:
    dst: ~/.zshrc
    src: zshrc
  nvim:
    dst: ~/.config/nvim
    src: config/nvim
  nvim-autoload:
    dst: ~/.config/nvim/autoload
    src: vim/autoload
    upignore:
      - '*'

profiles:
  Matts-MacBook-Pro.local:
    dotfiles:
    - ALL
  spin:
    dotfiles:
    - ALL
